on:
  push:
    tags:
      - '*'

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: false

  upload_assets:
    name: Publish for ${{ matrix.os }}
    needs: create_release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        name: [
            linux,
            windows,
            macos
        ]

        include:
          - name: linux
            os: ubuntu-latest
            artifact_name: "target/release/fasta_multi_grep"
            asset_name: "fasta_multi_grep-linux"
          - name: windows
            os: windows-latest
            artifact_name: "target/release/fasta_multi_grep.exe"
            asset_name: "fasta_multi_grep-window"
          - name: macos
            os: macos-latest
            artifact_name: "target/release/fasta_multi_grep"
            asset_name: "fasta_multi_grep-macos"

    steps:
      - uses: actions/checkout@v1

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Test
        run: cargo test

      - name: Build
        run: cargo build --release --locked

      - name: Upload assets
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ${{matrix.artifact_name}}
          asset_name: ${{matrix.asset_name}}